function navbar() {
  var html = "";
  html += '<nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">';
    html += '<div class="container">';
      html += '<a class="navbar-brand js-scroll-trigger" href="./index.html"><img alt="Brand" src="./img/saitama-university_1.jpg" style="height: 50px;"></a>';
      html += '<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">';
        html += '<span class="navbar-toggler-icon"></span>';
      html += '</button>';
      html += '<div class="collapse navbar-collapse" id="navbarResponsive">';
        html += '<ul class="navbar-nav ml-auto my-2 my-lg-0">';
          html += '<li class="nav-item">';
            html += '<a class="nav-link js-scroll-trigger" href="./index.html">トップ</a>';
          html += '</li>';
          html += '<li class="nav-item dropdown">';
            html += '<a href="" class="nav-link js-scroll-trigger dropdown-toggle" data-toggle="dropdown">研究概要<span class="caret"></span></a>';
            html += '<ul class="dropdown-menu" role="menu">';
              html += '<li><a href="./satoh-group.html" class="dropdown-item">佐藤研究室</a></li>';
              html += '<li><a href="./taniguchi-group.html" class="dropdown-item">谷口研究室</a></li>';
            html += '</ul>';
          html += '</li>';
          html += '<li class="nav-item">';
            html += '<a class="nav-link js-scroll-trigger" href="./index.html#research">最近の研究</a>';
          html += '</li>';
          html += '<li class="nav-item">';
            html += '<a class="nav-link js-scroll-trigger" href="./member.html">メンバー</a>';
          html += '</li>';
          html += '<li class="nav-item dropdown">';
            html += '<a href="" class="nav-link js-scroll-trigger dropdown-toggle" data-toggle="dropdown">業績/設備<span class="caret"></span></a>';
            html += '<ul class="dropdown-menu" role="menu">';
              html += '<li><a href="./achievements.html" class="dropdown-item">研究業績</a></li>';
              html += '<li><a href="./facility.html" class="dropdown-item">研究設備</a></li>';
            html += '</ul>';
          html += '</li>';
          html += '<li class="nav-item">';
            html += '<a class="nav-link js-scroll-trigger" href="./news.html">ニュース</a>';
          html += '</li>';
          html += '<li class="nav-item">';
            html += '<a class="nav-link js-scroll-trigger" href="./gallery.html">フォトギャラリー</a>';
          html += '</li>';
          html += '<li class="nav-item">';
            html += '<a class="nav-link js-scroll-trigger" href="./index.html#contact">連絡先</a>';
          html += '</li>';
        html += '</ul>';
      html += '</div>';
    html += '</div>';
  html += '</nav>';
  document.write(html);
}